### ISSUE TITLE
Paths don't work with Rails autoloader

### ISSUE THREAD

**Issue by jeremywadsack** [cfis/activejob-locking#1]
In my Rails app `config/initializers/activejob_locking.rb` file I have to write the following to load as adapter:

```
require "activejob/locking/adapters/redis-semaphore"
ActiveJob::Locking.options.adapter = ActiveJob::Locking::Adapters::RedisSemaphore
```

I believe the `require` line is necessary because the class names don't follow Rails' autoloading naming convention. The path would need to be `active_job/locking/adapters/redis_semaphore`. Note that Rails' `ActiveJob` code is in [the `active_job` folder as expected](https://github.com/rails/rails/tree/5-2-stable/activejob/lib/active_job).

I could open a PR to change this but I think it's worth a discussion — is this something that you want?

Also, if you changed this you'd want to release a major version or maybe retain the old paths for things like the adapters that people had previously `require`d so as not to introduce a breaking change.

**Comment by cfis** [comment]
If that change works, that I am good with it.
I'm guessing not many people use this gem, so a think a major release is good enough.

**Comment by jeremywadsack** [comment]
A simpler solution might be to add require all the adapters in `lib/activejob-locking.rb`. 

I've moved on to another gem, so I'll leave this to you to decide if you want to handle.

**Comment by cfis** [comment]
Ok - thanks.
