### ISSUE TITLE
Import all adapters by default

### ISSUE THREAD

**Issue by vicentealencar** [cfis/activejob-locking#13]
Using the latest version on my rails app I see that only the Memory adapter is being required by default. Is this by design?

**Comment by cfis** [comment]
Yes - see https://github.com/cfis/activejob-locking#adapter on how to configure

**Comment by vicentealencar** [comment]
Hey, thanks for responding. I don't see any instructions there actually about requiring the redlock module. I am having to manually add `require 'activejob/locking/adapters/redlock'` to get this to work. Are you sure this is by design?

```ruby
require 'activejob/locking/adapters/redlock'

if Rails.env.production?
  ActiveJob::Locking.options.adapter = ActiveJob::Locking::Adapters::Redlock
  ActiveJob::Locking.options.hosts = [ENV['REDIS_URL']]
else 
  ActiveJob::Locking.options.adapter = ActiveJob::Locking::Adapters::Memory
  ActiveJob::Locking.options.hosts = ['localhost']
end
```

**Comment by vicentealencar** [comment]
@cfis

**Comment by cfis** [comment]
Yes. Notice the tests do exactly that:

https://github.com/cfis/activejob-locking/blob/92bdcfb526c4bea30aced7b3352f11bbfb400fd7/test/test_helper.rb#L10

Loading all adapters automatically would require installing all of them.

Think of ActiverRecord. It does not automatically include all database drivers (postgresq, mysql, sqlite2, oracle, mysql). Instead you need to tell it which one you want via a yaml config file and then add it to your gem file. Same here, except you'll also need to add a require (although that could be done by ActiveLock).

**Comment by vicentealencar** [comment]
Cool, thanks for clarifying. Maybe it could be a good idea to add that instruction to the readme. I did end up spending a few minutes trying to figure this out (though it was not really a big deal)

**Comment by vicentealencar** [comment]
I can write those improvements to the readme file if you think that is a good idea

**Comment by cfis** [comment]
Yes, that would be great!
