### ISSUE TITLE
Tests are non-determinate

### ISSUE THREAD

**Issue by jeremywadsack** [cfis/activejob-locking#2]
I was looking to extend this with another lock option (and submit a PR) but I have now spent several days trying to get the test suite to work and have not had any luck. It seems to fail different tests on different adapters, randomly. I got this hooked up to Travis (so I could run in a different environment) and that [still fails](https://travis-ci.org/keylimetoolbox/activejob-locking).

I'm stumped about how to test this consistently. How do you make that work?

**Comment by cfis** [comment]
Yes, that is true.  I spent some time on trying to fix but eventually moved on.  Happy to take a pull request.

**Comment by jeremywadsack** [comment]
I couldn't figure this out.

Because of this I moved on to another `activejob-traffic_control` which seems to be the only ActiveJob-compatible locking gem that has a number of people using it. It also has a test suite that passes out-of-the box.

**Comment by cfis** [comment]
Ok, thanks.
