### ISSUE TITLE
Memory adapter using class instance variable for hash

### ISSUE THREAD

**Issue by gburgett** [cfis/activejob-locking#6]
Hello,

We had a problem with our jobs not being unlocked when using the Memory Adapter.  We tracked it down to the fact that `@hash` inside `self.lock` and `@hash` inside `self.unlock` are two different object IDs.

We added some debug logging to the Memory adapter:

```ruby
module ActiveJob
  module Locking
    module Adapters
      class Memory < Base
        @hash = Hash.new
        @mutex = Mutex.new

        def self.lock(key)
          @mutex.synchronize do
            puts "class lock #{key} #{@hash.object_id} #{@hash}"
            if @hash[key]
              false
            else
              @hash[key] = Time.now
            end
          end
        end

        def self.unlock(key)
          puts "class unlock: #{key} #{@hash.object_id} #{@hash}"
          @mutex.synchronize do
            @hash.delete(key)
            puts "deleted #{key}"
          end
        end
```

Notice the first `@hash` has object ID `47239310005400` and the second has `47007828954140`:
```
worker_1    | class unlock: activejoblocking:ReindexJob/Ministry 47239310005400 {}
worker_1    | deleted activejoblocking:ReindexJob/Ministry
worker_1    | 2019-09-11T18:29:42.756Z 1 TID-gqtg7pow1 ReindexJob JID-7d5a5088c3a4662c11f0742f INFO: done: 45.37 sec
web_1       | Started GET "/sidekiq/recurring-jobs/ReindexMinistries/enqueue" for 172.19.0.1 at 2019-09-11 18:32:00 +0000
web_1       | class lock activejoblocking:ReindexJob/Ministry 47007828954140 {"activejoblocking:ReindexJob/Ministry"=>2019-09-11 18:28:57 +0000}
```

This is why our ReindexJob is not being unlocked.

**Comment by cfis** [comment]
Huh - that's interesting. So multiple instances of the adapter are being created?  Can you track that down by chance?

**Comment by gburgett** [comment]
Now I feel dumb - Of course they're two different instances, we're using it in two different processes.  The main dissonance was that the "lock" is happening on enqueue - which is being done in our `web_1` process - while the "unlock" is happening when the job finishes, in our `worker_1` process.

Closing this issue as this is how the memory adapter is supposed to work.

**Comment by cfis** [comment]
No worries - the locking can definitely get confusing!
